runtime: go121

# This is needed to use GAE Mail API via `mailer` module.
# app_engine_apis: true

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
luci_gae_vars:
  luci-tree-status-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  luci-tree-status:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

entrypoint: >
  main -auth-service-host ${AUTH_SERVICE_HOST}
