service: default
runtime: go111

instance_class: F4_1G

handlers:
# Pubsub Handler.  This is strictly necessary because the default module
# contains a /.* routing rule, so if it was targeted directly, we still want
# login:admin to apply.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always
  login: admin

# Cron configuration update endpoint.
- url: /internal/cron/update-config
  script: auto
  secure: always

# Admin for service settings.
- url: /admin/.*
  script: auto
  secure: always
  login: admin

# Everything else goes here.
- url: /.*
  script: auto
  secure: always
