service: default
runtime: go111

instance_class: F4_1G

automatic_scaling:
  min_idle_instances: 10
  max_idle_instances: automatic  # default value
  min_pending_latency: 10ms
  max_pending_latency: 30ms  # default value
  max_concurrent_requests: 8  # note: the default value is 10

handlers:
# Single robots.txt file, must be served under root.
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Generated files in ResultUI.
- url: /static/dist
  secure: always
  static_dir: static/dist
  # All files have content hash in their filenames, so can be cached longer.
  expiration: 1d
  http_headers:
    # Set stale-while-revalidate to 4 weeks.
    Cache-Control: stale-while-revalidate=2419200

# For other static resources such as css and js files (including other ResultUI
# files).
- url: /static
  secure: always
  static_dir: static

# For admin resources.
- url: /admin/.*
  script: auto
  secure: always
  login: admin

# All internal handlers, such as cron.
- url: /internal/.*
  script: auto
  secure: always
  login: admin

# Pubsub Handler.  This is strictly necessary because the default module
# contains a /.* routing rule, so if it was targeted directly, we still want
# login:admin to apply.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always
  login: admin

# ResultUI frontend routes.
- url: /ui/.*
  secure: always
  static_files: index.html
  upload: index.html
  # Ensure that the page lives shorter than its dependencies.
  expiration: 10m
  http_headers:
    # Set stale-while-revalidate to 1 day.
    Cache-Control: stale-while-revalidate=86400

# The rest is handled by Go code.
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup
