service: default
runtime: go113

# luci_gae_vars is interpreted by gae.py, for apps deployed manually.
# It maps the app ID being deployed to values of vars used below.
luci_gae_vars:
  luci-change-verifier-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    FRONTEND_CLIENT_ID: 880120143479-shb008ruk2kms1178b14nhgjr47o4emm.apps.googleusercontent.com
    CONFIG_SERVICE_HOST: luci-config.appspot.com

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -frontend-client-id ${FRONTEND_CLIENT_ID}
  -config-service-host ${CONFIG_SERVICE_HOST}
