cron:

- url: /internal/tasks/c/sweep
  schedule: every 1 minutes

- url: /internal/cron/expire-actuations
  schedule: every 1 minutes

- url: /internal/cron/cleanup-old-entities
  schedule: every 6 hours
