service: default
runtime: go111

instance_class: F4_1G
automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /internal.*
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup
