service: default
runtime: go115

instance_class: F2

automatic_scaling:
  max_concurrent_requests: 80
  max_instances: 2

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
luci_gae_vars:
  example-app-id:
    AUTH_SERVICE_HOST: auth-service.example.com
    CONFIG_SERVICE_HOST: config-service.example.com
    TS_MON_ACOUNT: ts-mon@example.com

automatic_scaling:
  min_idle_instances: 1

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}

handlers:
- url: /.*
  script: auto
  secure: always
