service: default
runtime: go113

automatic_scaling:
  min_idle_instances: 1

entrypoint: >
  /usr/local/bin/start
  -auth-service-host chrome-infra-auth-dev.appspot.com
  -config-service-host luci-config.appspot.com
  -ts-mon-account app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com

handlers:
- url: /.*
  script: auto
  secure: always
