runtime: go120
instance_class: F4

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  luci-bisection-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    CONFIG_SERVICE_HOST: luci-config.appspot.com
    OAUTH_CLIENT_ID: 87540392498-pc1q4ttejqk41ius7d67sskjjk1g6jsr.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://luci-bisection-dev.appspot.com/auth/openid/callback
    TINK_AEAD_KEY: sm://tink-aead-primary
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
  luci-bisection:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    CONFIG_SERVICE_HOST: luci-config.appspot.com
    OAUTH_CLIENT_ID: 1080949892740-rs81jinf3677ocl04l1q7c8ga3vp4kll.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://luci-bisection.appspot.com/auth/openid/callback
    TINK_AEAD_KEY: sm://tink-aead-primary
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com

handlers:
- url: /.*
  script: auto
  secure: always

# Pubsub Handler.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-tink-aead-key ${TINK_AEAD_KEY}
  -frontend-client-id ${OAUTH_CLIENT_ID}
  -ts-mon-account ${TS_MON_ACCOUNT}
