service: default
runtime: go120

instance_class: F4_1G

automatic_scaling:
  min_idle_instances: 10
  max_idle_instances: automatic  # default value
  min_pending_latency: 10ms
  max_pending_latency: 30ms  # default value
  max_concurrent_requests: 8  # note: the default value is 10

# luci_gae_vars is interpreted by gae.py, for apps deployed manually.
# It maps the app ID being deployed to values of vars used below.
luci_gae_vars:
  luci-milo-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    CONFIG_SERVICE_HOST: luci-config.appspot.com
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    OAUTH_CLIENT_ID: 897369734084-d3t2c39aht2aqeop0f42pp48ejpr54up.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://luci-milo-dev.appspot.com/auth/openid/callback
    ROOT_SECRET: sm://root-secret
    TINK_AEAD_KEY: sm://tink-aead-primary
    REDIS_ADDR: 10.82.28.60:6379
    DS_CACHE: redis
    VPC_CONNECTOR: projects/luci-milo-dev/locations/us-central1/connectors/connector
    ANALYTICS_ID: UA-55762617-26
    LOGIN_SESSIONS_ROOT_URL: https://luci-milo-dev.appspot.com

vpc_access_connector:
  name: ${VPC_CONNECTOR}

handlers:
# Single robots.txt file, must be served under root.
- url: /robots.txt
  static_files: frontend/static/robots.txt
  upload: frontend/static/robots.txt

# Static resources such as css and js files.
- url: /static
  secure: always
  static_dir: frontend/static

# SPA frontend routes.
- url: /ui/(login|search|(inv|p|b|artifact|test)/.*)
  secure: always
  static_files: ui/out/index.html
  upload: ui/out/index.html
  # The resources are cached by the service worker. Don't serve the old content
  # when the service worker tries to fetch a new version.
  expiration: 0s

# Immutable SPA static resources.
- url: /ui/immutable
  secure: always
  static_dir: ui/out/immutable
  # All files have content hash in their filenames.
  # So they can be cached longer.
  expiration: 7d

# Host root-sw.js at root so it can have root scope.
- url: /(root-sw\.js(\.map)?)$
  secure: always
  static_files: ui/out/\1
  upload: ui/out/root-sw\.js(\.map)?$

# Other SPA static resources.
- url: /ui
  secure: always
  static_dir: ui/out
  # The resources are cached by the service worker. Don't serve the old content
  # when the service worker tries to fetch a new version.
  expiration: 0s

# The rest is handled by Go code.
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -cloud-error-reporting
  -root-secret ${ROOT_SECRET}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-required-scopes https://www.googleapis.com/auth/gerritcodereview
  -encrypted-cookies-expose-state-endpoint
  -redis-addr ${REDIS_ADDR}
  -ds-cache ${DS_CACHE}
  -analytics-id ${ANALYTICS_ID}
  -login-sessions-root-url ${LOGIN_SESSIONS_ROOT_URL}
