service: default
runtime: go111

instance_class: F4
automatic_scaling:
  max_concurrent_requests: 20
  min_idle_instances: 1

handlers:
- url: /rpcexplorer/?
  static_files: rpcexplorer/index.html
  upload: rpcexplorer/index.html
  secure: always

# The entire subpath is globbed because RPC Explorer uses native URL redirecting
# for sub-pages, and we want all of them to map to the same HTML file.
- url: /rpcexplorer/services/.*
  static_files: rpcexplorer/index.html
  upload: rpcexplorer/index.html
  secure: always

- url: /rpcexplorer
  static_dir: rpcexplorer
  secure: always

- url: /(internal|admin)/.*
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto
  secure: always
