runtime: go113

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
luci_gae_vars:
  example-app-id:
    AUTH_SERVICE_HOST: auth-service.example.com

entrypoint: >
  main -auth-service-host ${AUTH_SERVICE_HOST}
